;;; emacs-operator-adapter-cider.el --- CIDER runtime adapter -*- lexical-binding: t; -*-
(require 'emacs-operator-adapter-generic)
(require 'emacs-operator-adapter-repl)
(defun emacs-operator-cider-applicable-p (_context)
  (and (featurep 'cider) (or (derived-mode-p 'clojure-mode 'clojurescript-mode 'clojurec-mode) (bound-and-true-p cider-mode) (bound-and-true-p cider-repl-mode))))
(defun emacs-operator-cider--connection () (when (fboundp 'cider-current-connection) (condition-case nil (cider-current-connection) (error nil))))
(defun emacs-operator-cider--process (connection)
  (cond ((processp connection) connection) ((and connection (fboundp 'nrepl-connection-process)) (condition-case nil (nrepl-connection-process connection) (error nil)))))
(defun emacs-operator-cider--namespace () (when (fboundp 'cider-current-ns) (condition-case nil (cider-current-ns) (error nil))))
(defun emacs-operator-cider--ready-state ()
  (let* ((connection (emacs-operator-cider--connection)) (process (emacs-operator-cider--process connection)))
    (cond ((not connection) '(nil . "CIDER has no active nREPL connection."))
          ((and process (not (process-live-p process))) '(nil . "The CIDER nREPL process is not alive."))
          ((not (fboundp 'cider-nrepl-sync-request:eval)) '(nil . "This CIDER version does not expose synchronous nREPL evaluation."))
          (t '(t . nil)))))
(defun emacs-operator-cider-observe (_context)
  (let* ((connection (emacs-operator-cider--connection)) (process (emacs-operator-cider--process connection)) (namespace (emacs-operator-cider--namespace)) (ready (emacs-operator-cider--ready-state)))
    `(("feature_loaded" . t) ("connected" . ,(if connection t :json-false)) ("connection_name" . ,(and connection (format "%s" connection)))
      ("process_alive" . ,(if (and process (process-live-p process)) t :json-false)) ("namespace" . ,namespace)
      ("prompt_ready" . ,(if (car ready) t :json-false)) ("ready_reason" . ,(cdr ready)))))
(defun emacs-operator-cider-capabilities (_context)
  (let ((ready (car (emacs-operator-cider--ready-state))))
    `(("operations" .
       ((("name" . "eval_last_sexp")
         ("available" . ,(if ready t :json-false))
         ("channel" . "repl"))
        (("name" . "eval_defun")
         ("available" . ,(if ready t :json-false))
         ("channel" . "repl"))
        (("name" . "eval_region")
         ("available" . ,(if (and ready (use-region-p)) t :json-false))
         ("channel" . "repl"))
        (("name" . "test_ns")
         ("available" . ,(if (and ready (fboundp 'cider-test-run-ns-tests)) t :json-false))
         ("command" . "cider-test-run-ns-tests")
         ("channel" . "semantic"))))
      ("requires_connection" . t)
      ("result_contract" . ("stdout" "stderr" "value" "condition" "backtrace_handle")))))
(defun emacs-operator-cider--dict-get (response key)
  (cond
   ((hash-table-p response)
    (or (gethash key response) (gethash (intern key) response)))
   ((and (fboundp 'nrepl-dict-p)
         (fboundp 'nrepl-dict-get)
         (nrepl-dict-p response))
    (nrepl-dict-get response key))
   ((and (consp response) (eq (car response) 'dict))
    (let ((items (cdr response))
          value found)
      (while items
        (if (equal (car items) key)
            (setq value (cadr items)
                  found t
                  items nil)
          (setq items (cddr items))))
      (and found value)))
   ((listp response)
    (or (cdr (assoc key response))
        (cdr (assq (intern key) response))))))
(defun emacs-operator-cider--response-statuses (response)
  "Return RESPONSE status values as a list."
  (let ((status (emacs-operator-cider--dict-get response "status")))
    (cond
     ((null status) nil)
     ((vectorp status) (append status nil))
     ((listp status) status)
     (t (list status)))))

(defun emacs-operator-cider--failure-status (response)
  "Return the most specific nREPL failure status from RESPONSE, or nil."
  (let ((statuses (emacs-operator-cider--response-statuses response))
        failure)
    (dolist (candidate '("namespace-not-found" "eval-error" "unknown-session"
                         "unknown-op" "unknown-code-type" "interrupted" "error"))
      (when (and (null failure) (member candidate statuses))
        (setq failure candidate)))
    failure))

(defun emacs-operator-cider--eval-source (source params)
  (let* ((ready (emacs-operator-cider--ready-state))
         (namespace (emacs-operator-cider--namespace))
         (connection (emacs-operator-cider--connection))
         (timeout (emacs-operator-repl-timeout-seconds params))
         (operation (or (emacs-operator--get params "operation") "evaluation"))
         (metadata (emacs-operator-repl-source-metadata source operation)))
    (unless (car ready) (emacs-operator-signal "E_COMMAND_FAILED" (cdr ready)))
    (condition-case err
        (with-timeout (timeout (emacs-operator-repl-timeout-result "CIDER" namespace metadata))
          (let* ((response (cider-nrepl-sync-request:eval source connection namespace))
                 (value (emacs-operator-cider--dict-get response "value"))
                 (out (emacs-operator-cider--dict-get response "out"))
                 (stderr (emacs-operator-cider--dict-get response "err"))
                 (condition (or (emacs-operator-cider--dict-get response "ex")
                                (emacs-operator-cider--dict-get response "root-ex")
                                (emacs-operator-cider--failure-status response)))
                 (stack (emacs-operator-cider--dict-get response "stacktrace"))
                 (response-metadata
                  `(("nrepl_status" . ,(emacs-operator-cider--response-statuses response))
                    ("nrepl_ns" . ,(emacs-operator-cider--dict-get response "ns"))
                    ("nrepl_value_present" . ,(if value t :json-false)))))
            (emacs-operator-repl-result
             :stdout out :stderr stderr :value value :condition condition
             :backtrace-handle (and stack (format "cider:%sx" (sxhash-equal stack)))
             :namespace-or-package namespace
             :metadata (append metadata response-metadata)
             :completed (not condition))))
      (error
       (emacs-operator-repl-result
        :stderr (error-message-string err)
        :condition (symbol-name (car err))
        :namespace-or-package namespace :metadata metadata :completed nil)))))

(defun emacs-operator-cider-eval (params _context)
  (pcase (emacs-operator--get params "operation")
    ("eval_last_sexp" (emacs-operator-cider--eval-source (emacs-operator-repl-current-sexp-source) params))
    ("eval_defun" (emacs-operator-cider--eval-source (emacs-operator-repl-current-defun-source) params))
    ("eval_region" (emacs-operator-cider--eval-source (emacs-operator-repl-current-region-source) params)) (_ nil)))
(emacs-operator-register-adapter "cider" #'emacs-operator-cider-applicable-p #'emacs-operator-cider-capabilities :priority 80 :observe #'emacs-operator-cider-observe :eval #'emacs-operator-cider-eval :metadata '(("kind" . "repl") ("status" . "implemented") ("runtime" . "nrepl")))
(provide 'emacs-operator-adapter-cider)
