#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const rootPackagePath = path.join(root, "package.json");
const rootPackage = JSON.parse(fs.readFileSync(rootPackagePath, "utf8"));
const version = rootPackage.version;
if (typeof version !== "string" || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/.test(version)) {
  throw new Error(`Invalid root package version: ${String(version)}`);
}

const changes = [];
function syncJson(file, updater) {
  const full = path.join(root, file);
  const parsed = JSON.parse(fs.readFileSync(full, "utf8"));
  updater(parsed);
  const desired = `${JSON.stringify(parsed, null, 2)}\n`;
  const current = fs.readFileSync(full, "utf8");
  if (current !== desired) {
    changes.push(file);
    if (!checkOnly) fs.writeFileSync(full, desired);
  }
}

for (const file of [
  "packages/protocol/package.json",
  "packages/bridge-client/package.json",
  "packages/mcp-server/package.json",
  "packages/refactor-intelligence/package.json",
  "packages/benchmark/package.json",
  "packages/agent-experiment/package.json",
  "packages/test-harness/package.json",
  "apps/linux-host/package.json"
]) syncJson(file, (json) => { json.version = version; });

syncJson("packaging/mcpb/manifest.json", (json) => { json.version = version; });

const generatedPath = path.join(root, "packages/protocol/src/version.generated.ts");
const desiredGenerated = `// Generated by scripts/sync-version.mjs. Do not edit manually.\nexport const EMACS_OPERATOR_VERSION = ${JSON.stringify(version)} as const;\n`;
const currentGenerated = fs.existsSync(generatedPath) ? fs.readFileSync(generatedPath, "utf8") : "";
if (currentGenerated !== desiredGenerated) {
  changes.push("packages/protocol/src/version.generated.ts");
  if (!checkOnly) fs.writeFileSync(generatedPath, desiredGenerated);
}

if (checkOnly && changes.length > 0) {
  process.stderr.write(`Version metadata is out of sync with root ${version}:\n${changes.map((item) => `  - ${item}`).join("\n")}\n`);
  process.exitCode = 1;
} else {
  process.stdout.write(`${checkOnly ? "Version metadata is synchronized" : "Synchronized version metadata"}: ${version}${changes.length ? ` (${changes.length} file(s))` : ""}\n`);
}
