#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';
function fail(message,code=1){ process.stderr.write(`ERROR: ${message}\n`); process.exit(code); }
function arg(name,fallback=null){ const i=process.argv.indexOf(name); return i>=0&&i+1<process.argv.length?process.argv[i+1]:fallback; }
function has(name){ return process.argv.includes(name); }
function sha256File(file){ return crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'); }
function verifyFileManifest(root,manifestName,kind){ const manifestPath=path.join(root,manifestName); if(!fs.existsSync(manifestPath)) throw new Error(`Missing ${kind} manifest: ${manifestPath}`); const manifest=JSON.parse(fs.readFileSync(manifestPath,'utf8')); if(!Array.isArray(manifest.files)) throw new Error(`Invalid ${kind} manifest file list.`); const expected=new Map(manifest.files.map(item=>[item.path,item])); const actual=[]; const walk=(dir,rel='')=>{ for(const ent of fs.readdirSync(dir,{withFileTypes:true}).sort((a,b)=>a.name.localeCompare(b.name))){ const r=rel?`${rel}/${ent.name}`:ent.name; if(r===manifestName||ent.name==='.git') continue; const file=path.join(dir,ent.name),st=fs.lstatSync(file); if(st.isSymbolicLink()) throw new Error(`${kind} contains symlink: ${r}`); if(st.isDirectory()) walk(file,r); else if(st.isFile()) actual.push({path:r,bytes:st.size,sha256:sha256File(file)}); else throw new Error(`Unsupported ${kind} entry: ${r}`); } }; walk(root); const actualPaths=new Set(actual.map(x=>x.path)); for(const item of actual){ const locked=expected.get(item.path); if(!locked) throw new Error(`${kind} contains untracked file: ${item.path}`); if(locked.bytes!==item.bytes||locked.sha256!==item.sha256) throw new Error(`${kind} SHA-256 mismatch: ${item.path}`); } for(const p of expected.keys()) if(!actualPaths.has(p)) throw new Error(`${kind} missing locked file: ${p}`); return {manifest,manifestPath}; }
try{
  const slySource=path.resolve(arg('--sly-source')??fail('--sly-source is required',64)); const sbclRuntime=path.resolve(arg('--sbcl-runtime')??fail('--sbcl-runtime is required',64)); const host=arg('--host','127.0.0.1'); const port=Number(arg('--port','4005')); if(host!=='127.0.0.1') throw new Error('Slynk runtime may only bind to 127.0.0.1.'); if(!Number.isInteger(port)||port<1||port>65535) throw new Error('Slynk port must be an integer in 1..65535.');
  const sly=verifyFileManifest(slySource,'source-manifest.json','SLY source'); const sbcl=verifyFileManifest(sbclRuntime,'sbcl-runtime-manifest.json','SBCL runtime'); if(sbcl.manifest.runtime!=='sbcl'||typeof sbcl.manifest.executable!=='string'||typeof sbcl.manifest.home!=='string') throw new Error('Invalid SBCL runtime manifest metadata.');
  const loader=path.join(slySource,'slynk','slynk-loader.lisp'); if(!fs.existsSync(loader)||!fs.statSync(loader).isFile()) throw new Error('Locked SLY source has no slynk/slynk-loader.lisp.'); const executable=path.join(sbclRuntime,sbcl.manifest.executable); const home=path.join(sbclRuntime,sbcl.manifest.home); const startup=path.join(os.tmpdir(),`emacs-operator-slynk-${process.pid}-${crypto.randomBytes(4).toString('hex')}.lisp`); const escaped=loader.replaceAll('\\','\\\\').replaceAll('"','\\"'); fs.writeFileSync(startup,`(load \"${escaped}\")\n(slynk-loader:init)\n(slynk:create-server :port ${port} :interface \"127.0.0.1\" :dont-close t)\n(loop (sleep 60))\n`,{mode:0o600}); const args=['--noinform','--disable-debugger','--load',startup]; const env={...process.env,SBCL_HOME:home};
  if(has('--dry-run')){ process.stdout.write(`${JSON.stringify({ok:true,executable,args,env:{SBCL_HOME:home},sly_manifest:sly.manifestPath,sbcl_manifest:sbcl.manifestPath,sbcl_version:sbcl.manifest.version,sbcl_plan_sha256:sbcl.manifest.plan_sha256,host,port},null,2)}\n`); fs.rmSync(startup,{force:true}); process.exit(0); }
  const child=spawn(executable,args,{stdio:'inherit',shell:false,env}); const cleanup=()=>fs.rmSync(startup,{force:true}); const forward=(signal)=>{ if(!child.killed) child.kill(signal); }; process.on('SIGTERM',()=>forward('SIGTERM')); process.on('SIGINT',()=>forward('SIGINT')); child.on('error',error=>{ cleanup(); process.stderr.write(`ERROR: failed to start Slynk: ${error.message}\n`); process.exitCode=1; }); child.on('exit',(code,signal)=>{ cleanup(); if(signal) process.exitCode=128+(signal==='SIGTERM'?15:signal==='SIGINT'?2:1); else process.exitCode=code??1; });
}catch(error){ fail(error instanceof Error?error.message:String(error)); }
